### ISSUE TITLE
As a casual user, I want to be able to see what the current weather is in [insert specific location] because I’m curious. 

### ISSUE THREAD

**Issue by chrisnonfer** [wsu-cpts489-fa20/bp-weather#1]
Acceptance Criteria:
- [ ] User doesn't need to log in
- [ ] User can search for a specific location
- [ ] User can see the current weather at that location
- [ ] User does not have to add that location to their list of favorites

**Comment by chundhau** [comment]
What do you mean by "current weather?" (data fields)
