### ISSUE TITLE
favorite icon 

### ISSUE THREAD

**Issue by ByteSizeError** [wsu-cpts489-fa20/bp-weather#38]

**Comment by chrisnonfer** [comment]
want the favorite icon to be yellow if favorited, gray if not. currently, it flashed yellow if clicked on

**Comment by chrisnonfer** [comment]
move the icons to the upper right corner

**Comment by chrisnonfer** [comment]
make search bar look better?

**Comment by chrisnonfer** [comment]
change tab icon

**Comment by chrisnonfer** [comment]
- [x] Center search bar
- [x] Change tab icon
- [x] Move Favorite/Delete & History button to upper-right corner
- [ ] Favorite button is yellow if been favorited, gray if not
- [x] Changed styling for login buttons
- [x] Fixed empty table default
